version: '3.3'
services:
  postgres:
    image: postgres:13.2
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  webpack:
    build: .
    tty: true
    stdin_open: true
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
      - bundle_path:/bundle
    ports:
      - '3035:3035'
    env_file:
      - .env
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  web:
    build: .
    tty: true
    stdin_open: true
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - postgres
      - webpack
    volumes:
      - .:/app
      - bundle_path:/bundle
    env_file:
      - .env
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
      BUNDLE_PATH: /bundle/vendor
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  bundle_path:
  db:
